### ISSUE TITLE
Can ARI send a notification with callback URL when a certificate is about to expire unexpectedly or outside the planned schedule?

### ISSUE THREAD

**Issue by DongWangAakamai** [aarongable/draft-acme-ari#77]
Hi, our team is evaluating whether we can handle certificate revocation cases automatically. We're excited about ARI, but all the exposed interfaces currently rely on polling.

Given that we may manage up to 640k certificates, periodically querying each domain isn't practical. Would it be possible to provide a callback API during the certificate creation process? This way, we could receive notifications for unexpected revocations directly for the relevant domains.

**Comment by mholt** [comment]
I'm trying to find the thread, but this was discussed on the Let's Encrypt forums this year, and I'm not sure if a consensus was reached, but it seems that the burden is on the clients to poll. I advocated for a more client-scaling-friendly design, but that was rejected in favor of a simpler (?) ARI server implementation.

**Comment by webprofusion-chrisc** [comment]
@DongWangAakamai Cross referencing your post on the Let's Encrypt forum: https://community.letsencrypt.org/t/can-ari-send-a-notification-with-callback-url-when-a-certificate-is-about-to-expire-unexpectedly-or-outside-the-planned-schedule/227329

I do like the idea of an optional callback API (e.g. maybe a request to `/.well-known/acme-ari-notification` with the certID and account public key to prompt further checks or work).

Domains may not be websites and there is still a question of the opposite burden for a mass revocation ( as the CA would need to make the 650K notification calls to you), so instead perhaps it could just be a notification of the affected account ID (and public key), so the consumer can them go off and run their own ARI checks for each cert. 

Accounts would therefore need to be able to nominate a callback domain, which is an additional implementation burden for the CA, who many not currently have much other account metadata to handle.

**Comment by andrewachen** [comment]
Agree that a centralized callback for all certificates on an account would make sense, both from the scale and "domains may not be websites" perspectives.

**Comment by mholt** [comment]
Fair points, although I have a question:

> If the server sends a new notification every time it adjusts a cert's suggested renewal window, that could be an unbounded number of notifications depending on how its load balancing algorithm works.

Isn't the same true in the reverse? i.e. a load balancing algorithm that might change renewal windows often, the clients will have to poll just as frequently as a server would have to push out notifications, in order to get the updated window?

**Comment by aarongable** [comment]
I don't think so. The point of client polling is to get updates at a reasonable pace. The client can decide how quickly it wants to be informed based on the operational characteristics of the associated website, and the server can provide suggestions (Retry-After) based on the regulatory environment of its PKI. Meanwhile the server can be adjusting the suggested window as often as it likes, or even dynamically generating the suggested window when it receives each request.

That doesn't work in reverse. Dynamically-generated windows become impossible, as does Retry-After-based rate limiting (because each request from the ACME Server would be unique, not retries). It's not even necessarily clear which certificates belong to the same client identity -- do you cluster by ACME account ID, by hostname, by eTLD+1, or some combination? -- so it's very hard for the server to tell what "too much" traffic is for the client.
